hydra:
  output_subdir: null
  run:  
    dir: /tmp
train:
task: binary
data:
  task: binary
  text_encoder: google-bert/bert-base-uncased
  num_pos: 30
  num_neg: 90
para:
  text_encoder: google-bert/bert-base-uncased
  fea_dim: 128
  num_epoch: 50
  delta: 0.25
  alpha: 0.8
  num_pos: 30
  num_neg: 90
opt:
  name: AdamW
  lr: 5e-4
  weight_decay: 5e-5
sche:
  name: DummyLR

num_epoch: 50
batch_size: 32
seed: 2024
model: MoRE
dataset: HateMM
type: default
patience: 10